### ISSUE TITLE
Fix Virtualenv compatibility

### ISSUE THREAD

**Issue by migurski** [burnash/gspread#100]
`pip install gspread` fails inside [virtualenv](http://www.virtualenv.org/en/latest/) with a space in parent directory name. I’m running Python 2.7.5 on Mac OS 10.9, and when I attempt to install using pip, gspread tries to install itself in `/Library/Python/2.7/site-packages` where it encounters a permission failure. I can still correctly install gspread from the Git repo, using `python setup.py install`.

Steps to reproduce:
 1. `mkdir "/tmp/foo bar"` (note space in the name)
 2. `cd "/tmp/foo bar"`
 3. `virtualenv venv-foo`
 4. `source venv-foo/bin/activate.csh` (I use tcsh)
 5. `pip install gspread`

Here's [a log of the error](https://gist.github.com/migurski/2ca21380f7ad7c81b437).

When the parent directory has no space in its name, pip installs as expected:
 1. `mkdir /tmp/foo-bar`
 2. `cd /tmp/foo-bar`
 3. `virtualenv venv-foo`
 4. `source venv-foo/bin/activate.csh`
 5. `pip install gspread` now works.

**Comment by burnash** [comment]
@migurski Thanks for reporting the issue and sorry for the two years delay in reply.

I don't think the problem is related to `gspread`, though. In the linked install log, the pip version is `/usr/local/bin/pip` which looks like a system-wide installation. I'm not sure about the exact reason behind this particular failure, but similar permission-related errors [have been](http://stackoverflow.com/a/18199884/318359) [reported](http://stackoverflow.com/questions/29457435/pip-install-cssselect-weird-error) on StackOverflow. 

A space in a directory name is [another known issue](https://github.com/pypa/pip/issues/923). It is also unrelated to gspread.
