### ISSUE TITLE
Auto-Resize for rows

### ISSUE THREAD

**Issue by juliusdanek** [burnash/gspread#1022]
We have an auto resize for columns, can we add one for rows?

[https://github.com/burnash/gspread/blob/master/gspread/worksheet.py#L1046-L1067](https://github.com/burnash/gspread/blob/master/gspread/worksheet.py#L1046-L1067)

Or make the function usable for both, with a selector for dimension (row/column)?

**Comment by lavigne958** [comment]
Hi sure that is a great idea.

I'll add it the one of the coming releases.

Thanks for this proposal.

**Comment by mketer1** [comment]
Hi @lavigne958, I'm new to open source and would love to give this issue a shot. Could I be assigned this issue please

**Comment by lavigne958** [comment]
Hi ! Sure it would be a pleasure.

Give it a go and open a PR, we'll go from there.

**Comment by mketer1** [comment]
Thank you @lavigne958 ! I have cloned the code and plan to make a pull request containing worksheet.py once updated. I see that @juliusdanek mentions this feature was already created for columns but am failing to find it. I referenced the link provided but maybe I am just not understanding the code being linked. If possible, could you explain it please. I'm hoping to get this feature done as soon as possible to be able to work on others :)

**Comment by mketer1** [comment]
Ah, I see now. The lines mentioned were a little off. I'm assuming you were trying to mention the def columns_auto_resize function

**Comment by lavigne958** [comment]
Yes gspread has been updated since, some code has been added so the link with the line number is a little off but you found the right method.

The point here is to do something similar to: `_add_dimension_group` and `add_dimension_group_columns` and `add_dimension_group_rows`.

One function does the complete request and takes the dimensions as argument. That function starts with an underscore `_` so it's private. The other functions will call that private function with appropriate dimensions.

**Comment by mketer1** [comment]
Hi! I am beginning to run unit testing but am having trouble with getting it setup. I have downloaded my json file from google cloud services and am now on step 7 where it says 

Move the downloaded file to ~/.config/gspread/credentials.json. Windows users should put this file to %APPDATA%\gspread\credentials.json.

I'm currently on windows but am unsure as to where specifically this file is supposed to be placed

**Comment by mketer1** [comment]
Also, I have created a fork in order to regularly commit; however, when i tried running

git push

I received the error

fatal: The current branch auto_resize has no upstream branch.
To push the current branch and set the remote as upstream, use

git push --set-upstream origin auto_resize

After trying the command above, I was prompted to authenticate. I believe since I am not a contributor to this repository my authentication failed. Because of this I am unable to commit to my fork. Would you recommend I just work locally and then issue a pull request after testing, or would I be able to create a fork

**Comment by mketer1** [comment]
@lavigne958 whenever you get a chance can you take a look at the previous messages sent

**Comment by lavigne958** [comment]
Hi I double checked you did not forked the repository, I would recommend you to look at some tutorials on how to contribute on GitHub :wink:  like this one https://github.com/firstcontributions/first-contributions

BTW: no need to mention me on every message, I get a notification for every changes in this repository :sunglasses:

**Comment by mketer1** [comment]
> Hi! I am beginning to run unit testing but am having trouble with getting it setup. I have downloaded my json file from google cloud services and am now on step 7 where it says
> 
> Move the downloaded file to ~/.config/gspread/credentials.json. Windows users should put this file to %APPDATA%\gspread\credentials.json.
> 
> I'm currently on windows but am unsure as to where specifically this file is supposed to be placed

Could you please respond to this message. I'm having trouble with the unit testing setup

**Comment by lavigne958** [comment]
sure, 

you can either do:
## graphical solution

1. open you file explorer
2. un the address bar near the top input the follow address: `%APPDATA%` then press enter
3. from that folder, create a new folder `gspread`
4. place your creds (JSON file) in the `gspread` folder you just created
5. rename your creds file `credentials.json`

## local path solution

1. put your creds (JSON file) next to you python script.
2. in you script use the following syntax to use the local creds:
```python
import gspread
client = gspread.service_account(".\my_creds.json")
```
in the file path may be you need `\` or `/` depending if you are on windows or not.

**Comment by mketer1** [comment]
Hi! I would just like to provide in update! I have the issue resolved I believe. I just need to run regression testing in order to ensure nothing has broke. I plan on doing this within the next few days. Apologies for the slight delay, school has been taking up a lot of time. Thank you for your patience!

**Comment by lavigne958** [comment]
No worries. Take you time, thanks for the update.
Did you follow the link above on how to start on contributing on GitHub ?

**Comment by mketer1** [comment]
Hello! Yes I referenced the link. I believe I understand how to go about contributing properly on github now. I will try to create a fork later tonight and update you! Thanks again for such a helpful link :)

**Comment by mketer1** [comment]
Hello! I have officially created a fork and committed all my changes within there :)

Unfortunately I'm still having trouble running the unit tests. I followed the graphical solution; however, I could not find %APPDATA% within my file explorer, as this is a windows feature. [Following this stackoverflow post](https://apple.stackexchange.com/questions/28928/what-is-the-macos-equivalent-to-windows-appdata-folder), I have added a gspread folder with my credentials.json into my ~/Library/Application Support folder.

After this I created a new file test.py in the main gspread folder containing the following code [found in the docs](https://docs.gspread.org/en/latest/oauth2.html#oauth-client-id)

`import gspread

gc = gspread.oauth()

sh = gc.open("Example spreadsheet")

print(sh.sheet1.get('A1'))`

Following this, I ran the program and got an error, the traceback shown below

`Traceback (most recent call last):
  File "/Users/mohamadeter/Desktop/gspread/test.py", line 1, in <module>
    import gspread
  File "/Users/mohamadeter/Desktop/gspread/gspread/__init__.py", line 16, in <module>
    from .auth import oauth, oauth_from_dict, service_account, service_account_from_dict
  File "/Users/mohamadeter/Desktop/gspread/gspread/auth.py", line 12, in <module>
    from google.oauth2.credentials import Credentials
ModuleNotFoundError: No module named 'google'`

Once again,[ I followed this stack overflow post](https://stackoverflow.com/questions/36183486/importerror-no-module-named-google) and tried out both recommendations. The first, in which I installed the google api python client, I received the following error.

`ERROR: Cannot uninstall 'pyparsing'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
`

After trying the second solution in the stack overflow post, I was able to install google cloud successfully; however, I was unable to install google cloud vision. I received an environment error and am unsure as to how to go about resolving this issue. I have pasted the environment issue below if you are able to make sense of it

`ERROR: Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.12.0-py2.7.egg-info/PKG-INFO', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ/PKG-INFO', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ/PKG-INFO'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.12.0-py2.7.egg-info/SOURCES.txt', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ/SOURCES.txt', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ/SOURCES.txt'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.12.0-py2.7.egg-info/top_level.txt', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ/top_level.txt', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ/top_level.txt'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.12.0-py2.7.egg-info/dependency_links.txt', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ/dependency_links.txt', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ/dependency_links.txt'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.12.0-py2.7.egg-info', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-18JOaJ'")]`

Similarly, I have tried pip install --upgrade google-auth, but receive an environment error as well, shown below

`ERROR: Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/LICENSE', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/LICENSE', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/LICENSE'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/__init__.py', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/__init__.py', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/test.py', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/test.py', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/test.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/README', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/README', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/README'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/__init__.pyc', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/__init__.pyc', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/doc/enum.pdf', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/doc/enum.pdf', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/doc/enum.pdf'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/doc/enum.rst', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/doc/enum.rst', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/doc/enum.rst'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/doc', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/doc', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/doc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum/test.pyc', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/test.pyc', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE/test.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/enum', '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE', "[Errno 1] Operation not permitted: '/private/var/folders/9f/lt9pqq451fs49zd7j5tywmzc0000gn/T/pip-uninstall-8hvQkE'")]`

I have tried numerous ways in order to install the appropriate module but am having trouble. If you know a workaround or if I've missed something, please let me know. My updates to the source code are completed and I am just trying to run unit tests in order to ensure nothing has broken. For what it's worth, I am working on a 2019 macbook air on version 10.15.7. Thank you so much, apologies for such the long message.

**Comment by lavigne958** [comment]
Hi, well done.

About the config file. The second option where you place you credentials next to you python script is (trust me on this 😉) mich easier.

Place you JSON file in the main gspread folder then use the following syntax (assuming from your above example that you use `oauth` to authenticate, you have ways to authenticate `oauth` and `service_account`). 

```python
import gspread

client = gspread.oauth(credentials_filename="./my_creds.json")
```

This should allow you to run gspread using your creds.


About the second part (the tests), it is very common in python projects to store the dependencies in a file called `requirements.txt`. in gspread we have split this file in 2. So you have `lint-requirements.txt` and `test-requirements.txt.

On the top of that you'll find a file called `tox.ini` which contains all the possible actions we run in the CI. You don't need to install anything, tox will do it in a pyenv and run everything for you. All you need is tox

 ```
python -m pip install tox
```

Then simply run:

`tox -e py` and it will run the tests.
`tox -e lint` to run the linters.

**Comment by mketer1** [comment]
Hello once again!

Thank you for such a descriptive response, I was able to get the testing done locally and ran the regressions tests. All tests passed :)

With regard to the linter, on my first run, I was not passing the lint checks. I had trouble interpreting the linter (ended up figuring out after the fact), which led me to creating a new fork and running the linter after every X amount of code written. After this, I passed the linter as well

I have passed both regression tests and the linter as of now. I was hoping to create some unit tests for this specific feature but am unsure as to how to go about doing so seeing as this is a visual feature in which rows and columns get resized. If there is a way, could you please guide me in the right direction. If not, am I okay to submit a pull request?

Thanks again :)

**Comment by lavigne958** [comment]
Well done.

About the linter: you can run the following command, it will format your code so it passes the linter:

```
tox -e format
```

almost everything I explained here is described [CONTRIBUTING.MD](https://github.com/burnash/gspread/blob/master/.github/CONTRIBUTING.md) please read it through you will find most of the answers I gave you here.

About the height of a row or the width of a column you can find it here: [dimensionproperties](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#dimensionproperties)

On this web site you can find then entire Google Sheet API, you can find all the properties and informations you can get/set on a spreadsheet.

**Comment by mketer1** [comment]
Sounds good, Thank you! I have made a pull request if you'd like to take a look :)
