### ISSUE TITLE
Download PDF from Spreadsheet

### ISSUE THREAD

**Issue by cheak1974** [burnash/gspread#1035]
Lovely library.

I was wondering if it could maybe somehow be possible with the Google API to use the "Download -> PDF" function from the file menu in google sheets. This would be simply great to use a spread sheet as a template for table data. You could exchange the template data with real data and generate a PDF document for sending it away. Just dreaming ....

If this is not possible to do with the google API then delete this feature request.

best regards

Chris

**Comment by lavigne958** [comment]
Hi this is a great idea.

I found the Google drive API that allows us to export a file.

I need to plan that feature then we can make it happen 😉

Here is the API:

https://developers.google.com/drive/api/v3/reference/files/export

**Comment by 100paperkite** [comment]
I worked on this and made a PR 😊

**Comment by lavigne958** [comment]
Hi I saw the PR. 

We need to think about the new feature

- do we return the PDF content or do we handle saving the PDF to a file ?
- should we offer other content type ?

I think having the method in the client is nice because it saves some API calls (the API calls necessary to open the spreadsheet)

**Comment by 100paperkite** [comment]
@lavigne958 

- I also thought about how to make user save a PDF file... I think returning the PDF content would be more flexible than saving the PDF file in API (because the latter requires a saving path, and then API should verify the path)
- I think it's good to offer other content types since (maybe) some users want other content types in the future, and working on it is not that hard (just changing a mime-type)

**Comment by lavigne958** [comment]
Agreed,

Can you please update your PR so the method becomes something like `export(file_id, format=exportFormats.PDF)`

It would be very nice if you add a new `namedtuples` that contains the list of potentials export format we offer with a simple name, you can see some examples in the file 
https://github.com/burnash/gspread/blob/c1ad0ceca31620814affb1be8a5fde845f566f64/gspread/utils.py#L35-L41

if you do so please add the new named tuple bellow the existing ones :slightly_smiling_face:

Side note:
please have a look to the following file https://github.com/burnash/gspread/blob/master/.github/CONTRIBUTING.md

it will give you all the necessary instructions on how to run CI locally and the linters etc. so your PR can pass the tests :wink: 

Thank you for your contribution and you time

**Comment by 100paperkite** [comment]
Thanks for the explanation! I'll update the PR
