### ISSUE TITLE
Update google dependencies

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1230]
Google libraries are currently pinned to:

https://github.com/burnash/gspread/blob/7f12b2dcb7f96f433e0ee7f64661a9345e315cc2/pyproject.toml#L29

They could be updated. Each has a new major release.

https://github.com/googleapis/google-auth-library-python/releases/tag/v2.0.0

https://github.com/googleapis/google-auth-library-python-oauthlib/releases/tag/v1.0.0

From a quick glance it looks like they would work fine to update, as the breaking changes may not affect us.

@lavigne958 you have more idea on the auth side?

**Comment by lavigne958** [comment]
I remember I had issues with the libraries, I pinned them because they introduce some breaking change in their API at some point.

We can take the chance of the 6.0.0 release to upgrade them.

But they are very touchy/picky I tend not to change them so much :laughing: 

We can give it a try if it works fine
We must check:

- auth by oauth
- auth by service_account

**Comment by alifeee** [comment]
This makes sense.

If there not a great reason to change them, and you think there could be issues, we could just leave them.

**Comment by alifeee** [comment]
not a great reason to change

**Comment by lavigne958** [comment]
yes and setting this dependency to high version, specifically setting something like in the requirements: `google-auth>=2.21.0` instead of currently `1.12.0`, will enforce anyone using `gpsread` to have that specific version and if they use `gspread` alongside other packages then it might just break.

Let say a user has a package that requires `google-auth>= 1.0.0` and `google-auth<2.0.0` then if we just update to the latest we break this user's code. or enforce the user to keep using older version of gspread until all its dependency are matching.

The best way is to identify what we use in `google-auth` and `google-auth-oauthlib` and find the lowest version that provides that.

We can update any minor version but no major version (as usual _breaking changes_ :disappointed: )

what we can do is: check what is actually new in the new major release (reading their changelog) and see if anything is useful to us or solves some of our issues and then having a new major release of gspread can upgrade the dependency to a new major version bump.

**Comment by lavigne958** [comment]
Thinking about it we can tell dependabot to only upgrade minor versions for these library. for example since last update we can upgrade quite  a few minor versions. that could helps us.
