### ISSUE TITLE
question on sheet.range() function

### ISSUE THREAD

**Issue by jason79** [burnash/gspread#124]
for the range "A1:B3" right now the list is 

[A1,A2,A3,B1,B2,B3]

Is there a setting or switch to make it automatically formatted into a grouped list like so:

[[A1,A2,A3],[B1,B2,B3]]

would make the data much more easy to address once in python

**Comment by msuozzo** [comment]
This is an interesting proposal. I feel like is does have a legitimate use case and utilizing `Worksheet.range` would allow it to be performed with a single HTTP request.

I'll mark it as a feature request. I'd like to see whether there's broader interest for this.

**Comment by burnash** [comment]
Since [3.3.0](https://github.com/burnash/gspread/blob/master/HISTORY.rst#330-2020-03-12) there's a pair of [`Worksheet.get()`](https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Worksheet.get) / [`Worksheet.update()`](https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Worksheet.update) methods that you can use to fetch and update a range of cells while keeping the array-like shape of data.
I'm closing this issue. Please feel free to open a new issue if this solution does not work for you.
