### ISSUE TITLE
Fix BackOffHTTPClient not returning error 403

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1268]
Currently, we cannot reliably test raising of `PermissionError` (see #1244 #1245).

This is because for the tests, a [`BackOffHTTPClient`] is used, which has problems returning 403 errors.

https://github.com/burnash/gspread/blob/6259c2be9fae8e7567ea1796dd98e3c0d2570672/gspread/http_client.py#L329-L335

https://github.com/burnash/gspread/blob/6259c2be9fae8e7567ea1796dd98e3c0d2570672/tests/client_test.py#L110-L127

[`BackOffHTTPClient`]: https://github.com/burnash/gspread/blob/6259c2be9fae8e7567ea1796dd98e3c0d2570672/gspread/http_client.py#L310

If this is fixed, the test can be un-skipped.

With the normal HTTP client, it works fine (returns `PermissionError` immediately)

**Comment by lavigne958** [comment]
In order to resolve this issue we should be more accurate at when we retry a request by waitting.

I found the following article from google drive doc that mentions a keyword we can match `userRateLimitExceeded` located in the error message under `error.errors[0].reason` if we find the error code 403 we should look for that value, if present then delay the request if not just keep raising the error. that could allow use to trigger a 403 error right away on forbidden access to a spreadsheet.

https://developers.google.com/drive/api/guides/handle-errors#resolve_a_403_error_user_rate_limit_exceeded

**Comment by alifeee** [comment]
This sounds like a good plan.

I would implement it. However, I am not sure if is possible to reliably get a "rate limit exceeded" request (in order to test that the logic works properly). So I do not want to push code that might not work.

Any idea if it would be possible to reliably hit the rate limit, without also breaking the other tests?

**Comment by alifeee** [comment]
According to @lavigne958: "The Drive API is the best candidate to get an example of a 403 rate limit request. It has a max of some couple thousand requests per second"

**Comment by lavigne958** [comment]
> According to @lavigne958: "The Drive API is the best candidate to get an example of a 403 rate limit request. It has a max of some couple thousand requests per second"

exactly it's 20000 per 100 seconds.

We should be able to reach them and read the error code. but we can already read the error JSON format here:

- daily limits: https://developers.google.com/drive/api/guides/handle-errors#daily-limit
- rate limit exceeded: https://developers.google.com/drive/api/guides/handle-errors#rate-limit

thinking about it, in the constructor of a `APIError` we parse the error.

Knowing more about the format with the above links we could possibly parse it a bit more and raise some exception for quota then raise it to the user it would help a lot the users I suppose to catch quota exceptions :thinking: 
this would be a different ticket of course
