### ISSUE TITLE
alternative to `worksheet.get_all_records()` for specific ranges or max num of rows

### ISSUE THREAD

**Issue by AndrewBasem1** [burnash/gspread#1294]
**Is your feature request related to a problem? Please describe.**
The `worksheet.get_all_records()` is a convenient method to download the sheet data into structured dictionary format, but it stops being convenient when the worksheet I'm trying to download data from has way too many rows, and I only need a small subset (due to bad internet connection, just wanting a maximum number of rows, so on..)

**Describe the solution you'd like**
Creation of a new method that could be called `.get_some_records()` or `.get_records_from_range()` that will only download a certain range only, or a maximum number of `n` rows for example.

**Describe alternatives you've considered**
Getting the data as list of lists and doing the dictionary conversion myself, pretty easy to do, but still would be helpful if it was already present in the gspread module itself directly

**Comment by alifeee** [comment]
Hi :). This is a very clear request, thank you.

What you propose is, in effect, pagination. Such that you want to call `get_all_records` with a "first row index" and a "last row index", and only be returned values from this region. This sounds like it would be a good feature.

Either we can alter `get_all_records` (a bit misleading) or add a new function `get_records` which takes a start/end row index (and then `get_all_records` can just call `get_records`). We would have to change this line

https://github.com/burnash/gspread/blob/4e0f6121d55e5a21af8f5f709c1e8be74308cde4/gspread/worksheet.py#L547

to something like

```python
header_row = self.get_values(header_row)
data = self.get_values(f"{first_row_index}:{last_row_index}")
```

and the rest of the function could remain the same.

----------

If you would like to help implement this issue, see the [contributing guide], and I can offer my help and advice.

Otherwise, we will implement it (eventually).

[contributing guide]: https://github.com/burnash/gspread/blob/master/.github/CONTRIBUTING.md

**Comment by AndrewBasem1** [comment]
Yes, I'll start working on this! expect a PR soon
