### ISSUE TITLE
Remove unused parameter or use it

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#1332]
## Overview

I noticed the following unused parameter, we should either use it, or remove it. 

https://github.com/burnash/gspread/blob/f6d1b1b79752503012230f595a4f55ebd231a702/gspread/worksheet.py#L574

I'll have a look at the code itself a bit longer to check what is best.

**Comment by alifeee** [comment]
Hi. `use_index` was added by #1301 (see https://github.com/burnash/gspread/pull/1301#issuecomment-1732494225). Currently, it does nothing if not set to `use_index=0`

https://github.com/burnash/gspread/blob/f6d1b1b79752503012230f595a4f55ebd231a702/gspread/worksheet.py#L643-L646

It exists so that #808 can be implemented. If `use_index = 1` were used, then we could get records using the first column as headers, instead of the first row.

**Comment by lavigne958** [comment]
alright so for now:
- it has no impact
- if a user set it to the wrong value it will raise an exception and stop the program
- we don't plan to use it so far 

so let's remove it. it's nothing big we can add it back later when we need.

I suggest.

**Comment by alifeee** [comment]
agreed. made a PR
