### ISSUE TITLE
gspread numberFormat is not applied for a date

### ISSUE THREAD

**Issue by rgoubet** [burnash/gspread#1368]
**Important**: Please do not post usage questions here. 
To get a quick response, please ask a question on Stack Overflow using `gspread` tag.
See existing questions: https://stackoverflow.com/questions/tagged/gspread

---

**Describe the bug**
When passing `numberFormat` for types DATE or TIME, the format is not applied.

**To Reproduce**
```python
sh = gc.create("new")
ws = sh.get_worksheet(0)
ws.update("A1", "20/10/2023")
ws.format(
    "A1",
    {
        "numberFormat": {
            "pattern": "dd-mmm-yyyy",
            "type": "DATE",
        },
        "textFormat": {"bold": True},
    },
)
```

**Expected behavior**
When opening the spreadsheet in Google Spreadsheet, the cell should be show as "20-oct-2023". However, while the cell A1 is in bold, the content is still a string "20/10/2023".

**Code example***
See above

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]: Linux
- Python version: 3.11
- gspread version: 5.12.2

**Comment by alifeee** [comment]
Hi! Thanks for the issue :)

Your problem is not with `format`, it is with `update`.

The code 

```python
ws.update("A1", "20/10/2023")
```

places the string "20/10/2023" in cell A1. This is not a date, but a string. It is the equivalent of typing `'20/10/2023` (unformatted string). You can see this apostrophe in the formula editor

![image](https://github.com/burnash/gspread/assets/13833017/e6cdf875-37f3-4e20-afae-ca478d6e806f)

It looks like you want a date. You can use `value_render_option` to ask Google to turn your string into a date, using

```python
from gspread.utils import ValueRenderOption

ws.update(
  "A1",
  "20/10/2023",
  value_input_option=ValueInputOption.user_entered,
)
```

Then, your `format` will work properly.

Thanks :)

**Comment by rgoubet** [comment]
Yes, that's right! It even works if the input is a pandas dataframe (converted to a list). Note a small typo in your import statement where `ValueInputOption` should be imported rather than `ValueRenderOption`.

Thanks!
