### ISSUE TITLE
Update all artifacts to remove python 3.7

### ISSUE THREAD

**Issue by ckoppelman** [burnash/gspread#1391]
**Describe the bug**
When installing gspread using pip or other such tools, it is helpful to know which versions of python your package supports.  Currently, your [pyproject.toml](https://github.com/burnash/gspread/blob/master/pyproject.toml#L32) says, `requires-python = ">=3.7"` instead of the new `requires-python = ">=3.8"`.  [`tox.ini`](https://github.com/burnash/gspread/blob/master/tox.ini#L2) also mentions py37. 

**To Reproduce**
1. Read the documents.

**Expected behavior**
I expect that when dropping support for a minor version of python, you update the technical artifacts that announce versions supported.

**Comment by alifeee** [comment]
Hi, thanks for noticing this :)

I did remove Python 3.7 in #1234, but the files I removed it from were moved in #1231, effectively re-adding references to 3.7.

Because of the way that the git branches were set up the initial change was not brought into master properly. This should not be the case with future changes. It was unfortunate that this happened here. We'll make a minor release to clarify this.

**Comment by ckoppelman** [comment]
Is there a way to remove 6.0.0 from pypi?  It seems this will cause dependency errors in other applications, as well.

**Comment by alifeee** [comment]
> Is there a way to remove 6.0.0 from pypi? It seems this will cause dependency errors in other applications, as well.

Yes, when we remove it from `pyproject.toml` and make a release, Python 3.7 will be removed from the PyPi. If you feel like it, you could make this small PR ;) (otherwise I'll do it soon) 

> Also, .... sorry about the snark above. It was more snark at the bug template than at the code, which is a totally reasonable merge mistake!

Haha, it's no worries, all in good faith. I admit I found it funny that you stuck to the template :)
