### ISSUE TITLE
add `value_render_option` to examples (automatic conversion of currency)

### ISSUE THREAD

**Issue by nick-youngblut** [burnash/gspread#1416]
At least for `gspread==6.0.0`, it appears that `worksheet()` can only return currency-formatted column values as strings (e.g., `'$2,599.20'`). So, each user of gspread must write their own custom parser for the standard task of converting currency strings to floats for each currency column in each loaded Google Sheet. It would be helpful if such a currency conversion was available for `worksheet()` (similar to the [GoogleSheets4](https://googlesheets4.tidyverse.org/) R package).

**Comment by alifeee** [comment]
Hi :) thanks for the issue

Firstly, you may be looking for `ValueRenderOption`. See the [`get` documentation](https://docs.gspread.org/en/v6.0.0/api/models/worksheet.html#gspread.worksheet.Worksheet.get). If you set this to `gspread.utils.gspread.utils.ValueRenderOption.unformatted`, you should get currency formatted values as numbers instead. See the bottom of this comment for a code example.

I believe we should add this example to the project README.

If this doesn't work, your spreadsheet may be formatted incorrectly. See the following:

By default, Google Sheets uses your local currency to format cells. This means, as you type, "£12" is turned into "12". If you type "$12", it is not recognised as a currency, so it remains "$12". I illustrate this via the diagram:

![image](https://github.com/burnash/gspread/assets/13833017/22746be4-fa44-451c-aac4-322cee78fb31)

This means that when you use `gspread` to get the unformatted value, you get your default currency as numbers, and other currencies as strings.

The solution to this is to add a custom currency formatting in Google Sheets:

![image](https://github.com/burnash/gspread/assets/13833017/336fa89f-77b0-494c-af9a-3233d0a4a8b4)

![image](https://github.com/burnash/gspread/assets/13833017/854a85f0-9835-4b21-9f1d-a92a6766b63e)

Now, instead of typing "$12", you can type "12", and it will be formatted nicely as a currency. As I understand it, this just prepends/appends text to your numbers for display. Please see this example diagram:

![image](https://github.com/burnash/gspread/assets/13833017/384a2cc9-ab64-43e0-a72f-dda9b8886f0d)

So then, you can use gspread as such:

```bash
> from gspread.utils import ValueRenderOption
> cells1 = worksheet.get("A1:B2")
[['$12.00']]
> cells2 = worksheet.get("A1:B2", value_render_option=ValueRenderOption.unformatted)
[[12]]
```

Let me know if that solves your issue. thanks :)

**Comment by nick-youngblut** [comment]
Thanks for the quick reply! 

The following worked for my needs:

```
import gspread
from gspread.utils import ValueRenderOption
import pandas ad pd

wks = gc.open_by_url(url).worksheet(sheet_name)
DF = pd.DataFrame(wks.get_all_records(value_render_option=ValueRenderOption.unformatted))
```

I now see the `value_render_option` in docs, and what it actually means, in regards to currency formatting. Thanks for your help!

**Comment by alifeee** [comment]
> I now see the value_render_option in docs, and what it actually means, in regards to currency formatting. Thanks for your help!

No worries, I hope you have fun with your numbers :)

As I said, I think we should add `value_render_option` to the readme, so I will open this and do that (soon™)

**Comment by lavigne958** [comment]
Hey @alifeee is that ok with you if we remove this from 6.1.0 and put it in 6.2.0, so we can release 6.1.0 with what we currently have ? I feel like what was merge after the last tag has been here for some weeks and could be released.

if that's ok with you.

**Comment by alifeee** [comment]
> Hey @alifeee is that ok with you if we remove this from 6.1.0 and put it in 6.2.0, so we can release 6.1.0 with what we currently have ? I feel like what was merge after the last tag has been here for some weeks and could be released.
> 
> if that's ok with you.

I think we should make this change as it is just a documentation change, so should not be difficult or take too long.

**Comment by lavigne958** [comment]
> > Hey @alifeee is that ok with you if we remove this from 6.1.0 and put it in 6.2.0, so we can release 6.1.0 with what we currently have ? I feel like what was merge after the last tag has been here for some weeks and could be released.
> > 
> > if that's ok with you.
> 
> I think we should make this change as it is just a documentation change, so should not be difficult or take too long.

Right I misunderstood the issue. I thought it would be adding a new value render option 😑

Right documentation only is of course quick enough to keep it here 👌
