### ISSUE TITLE
Unable to read public readonly spreadsheet

### ISSUE THREAD

**Issue by martin-flower** [burnash/gspread#1429]
**Describe the bug**
Unable to read public readonly spreadsheet

**To Reproduce**
This is the "shared link":
https://docs.google.com/spreadsheets/d/1gGF4o1C-ytu0aaCdVm6D73wGwPCMvETpqsScTXQzAPM/edit?usp=sharing

gspread _does_ work with my own hello world spreadsheet

**Environment info:**
- Operating System macOS 14.2.1
- Python version 3.12.0
- gspread version 6.0.2

**Stack trace or other output that would be helpful**
SpreadsheetNotFound: <Response [200]>

**Comment by lavigne958** [comment]
Hi thank you for raising this issue.

Please provide us the line where your code breaks and the 5 lines of code before that so we can investigate if it's a problem with your code or with gspread.

**Comment by martin-flower** [comment]
Here is the complete code

```py
import gspread

def sheet_api():
    gc = gspread.service_account(filename='./config/service_account.json')
    # public spreadsheet - all three references to same spreadsheet
    try:
        sh = gc.open("https://docs.google.com/spreadsheets/d/1gGF4o1C-ytu0aaCdVm6D73wGwPCMvETpqsScTXQzAPM/edit#gid=1164501076")
        print(sh.sheet1.get('A1'))
    except gspread.exceptions.SpreadsheetNotFound:
        pass
    try:
        sh = gc.open("1gGF4o1C-ytu0aaCdVm6D73wGwPCMvETpqsScTXQzAPM")
        print(sh.sheet1.get('A1'))
    except gspread.exceptions.SpreadsheetNotFound:
        pass
    try:
        sh = gc.open("CheckWatt serial numbers")
        print(sh.sheet1.get('A1'))
    except gspread.exceptions.SpreadsheetNotFound:
        pass
    
    # private spreadsheet works
    sh = gc.open("torsdag")
    print(sh.sheet1.get('A1'))

# python3 sheet.py
def main():
    sheet_api()

if __name__ == "__main__":
    main()

```

**Comment by lavigne958** [comment]
Hi thank you for sharing.

The issue is located here:

```python
sh = gc.open("https://docs.google.com/spreadsheets/d/1gGF4o1C-ytu0aaCdVm6D73wGwPCMvETpqsScTXQzAPM/edit#gid=1164501076")
```

As mentioned in the documentation [here](https://docs.gspread.org/en/latest/api/client.html#gspread.Client.open)

The method `open()` takes a parameter `title` which is the title of the spreadsheet.

It then searches through all you private + shared filed for the file matching that name.

If you wish to open a public spreadsheet file and you don't own it, please use the `open_by_key()` method, see example [here](https://docs.gspread.org/en/latest/api/client.html#gspread.Client.open_by_key)

**Comment by martin-flower** [comment]
Confirmed! `open_by_key()` is the answer! Thanks for the quick response!
