### ISSUE TITLE
No spreadsheets when using SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by butako** [burnash/gspread#185]
Hello,
I am trying to use the SignedJwtAssertionCredentials per example below. However I am finding that gc.openall() is not returning any spreadsheets. gc.authorize() succeeds, but openall() returns 0 spreadsheets.
If I switch over to the regular OAuth2 credential method it works just fine (as described here: https://github.com/burnash/gspread/wiki/How-to-get-OAuth-access-token-in-console%3F) 

Any idea why Signed Credentials cannot see any spreadsheets in my account please?

```python
	with open('mykey.p12') as f:
		key = f.read()

	scope = ['https://spreadsheets.google.com/feeds', 'https://docs.google.com/feeds']
	email = 'snip@developer.gserviceaccount.com'
	credentials = SignedJwtAssertionCredentials(email, key, scope)
	assert not credentials.access_token_expired

	gc = gspread.authorize(credentials)

	scs = gc.openall()
	for sc in scs:
		print sc.id
```

**Comment by ekolesnikov** [comment]
Hi Butako

If you still have the problem: the @developer.gserviceaccount.com is you app's service account, not your personal one, hence it has its own Google Drive etc. If you have your own domain, you can impersonate users (i.e. yourself) through domain-wide delegation (https://developers.google.com/accounts/docs/OAuth2ServiceAccount).
Alternatively, you can share the spreadsheets (or the whole folder) with your snip@developer.gserviceaccount.com Google App Engine service account.

**Comment by magnet** [comment]
Thank a lot @ekolesnikov 
This need to be more visible in the documentation. I've just upgraded to using OAuth2 since the old credentials API has been deprecated, and even though I had some operation to do to give access to my spreadsheets, I had no idea where to go, and no will to waste any more time :). It's not obvious but those emails are valid Google IDs that you can share documents with (File > Share in the doc you want to share).

**Comment by msuozzo** [comment]
Added separate issue to address this. Follow along in #315
