### ISSUE TITLE
Accessing a named range

### ISSUE THREAD

**Issue by ghost** [burnash/gspread#198]
Thanks for this library. I am new to it so pardon me if this is an easy one.

How do you access a named range? For instance, I have cell B3, which has a named range of "mycell". I try wks.acell('B3').value or even wks.acell('B3') but that just gives me the cell's value. The API says I can access the cell's range:
https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet#getRangeByName(String)

**Comment by burnash** [comment]
Thanks for the feedback!

Well, this is not so easy one :) I'm afraid it is not possible at the moment to access a named range via gspread due to the Spreadsheet API limitation. The API you're referring to is the API for [Google Apps Script](https://developers.google.com/apps-script/) (Google's own JavaScript-like cloud based scripting language). I don't know any non-hacky way to access this API from outside GAS environment. 

gspread uses [Google Sheets API](https://developers.google.com/google-apps/spreadsheets/) for managing spreadsheets. And I can't find any reference to named ranges in the docs.

**Comment by motin** [comment]
@burnash Time to re-open this? Gsheets v4 api has support for this. Given `spreadsheet_id` and `credentials`, this returns the named ranges in a document:
```
from googleapiclient.discovery import build
service = build('sheets', 'v4', credentials=credentials)
ranges = []
fields = "namedRanges"
request = service.spreadsheets().get(spreadsheetId=spreadsheet_id, ranges=ranges, fields=fields)
response = request.execute()
print(response)
```

**Comment by burnash** [comment]
Thanks, @motin. I agree.

**Comment by lavigne958** [comment]
This is already solved in latest version of Gspread. One cas use `get('MyRange')` or `get_values('MyRange')` in order to access a named range.

Closing this issue.
