### ISSUE TITLE
Supporting unicode: using ElementTree.toString w/ default encoding of ascii

### ISSUE THREAD

**Issue by Allard-Timothy** [burnash/gspread#206]
The update_cell function uses ElementTree.toString() but uses the default encoding of ascii.  You're setting the encoding in the XML header for requests to utf-8 so it's possible, but you lose that when you call ElementTree.toString().  This should support unicode as that is the standard.

**Comment by msuozzo** [comment]
You should be able to pass unicode objects to `update_cell`.

There was an issue with unicode in `update_cells` but this has been fixed with 90d62248675aadc4c9546c7e87f28197f071345c.

This was actually a weird issue with XML declaration headers (check out the commit message) instead of the `ElementTree.tostring` encoding but thanks a lot for bringing this to my attention.
