### ISSUE TITLE
Create an empty spreadsheet

### ISSUE THREAD

**Issue by Opalo** [burnash/gspread#221]
Does gspread support creating new empty spreadsheet?

**Comment by miklevin** [comment]
This just happens to be what I'm looking to do too.

**Comment by burnash** [comment]
@Opalo @miklevin Unfortunately, it doesn't.

**Comment by miklevin** [comment]
Okay. I'm working my way through it. I think this is for a reason. Google I believe is principled against mechanized auto created files. It'd fill the Internet with garbage all over again. As with actions in Google+, every action must be double-verified deliberate. Yesterday, 4/20/15, was the sunset date for using the Google Lists API that predated the Drive API. Let all old apps break that used to be allowed to mechanize file creation without a paid metered API to answer to. So, it's just a suspicion that I feel reinforced every time I make a new Spreadsheet and realized it "doesn't really exist" until the moment I actually do something to a cell somewhere on it or change it's name from "Untitled spreadsheet". So, I will make the UI of my app tell user to create a spreadsheet with such-and-such a name, so that this app can interact with it (by virtue of knowing what filename to look for). My virtual machine code execution footprint is like only about 60MB and adding the actual gdata API or one of the other approaches that do exist are so expensive in software dependency terms, that I'd rather just talk the user through it.

**Comment by cstarner** [comment]
I've updated gspread to include a function that creates a blank spreadsheet. I will submit it as soon as I have a moment to figure out how.

**Comment by miklevin** [comment]
Hi @cstarner cstarner. The world is waiting! If you're not in it for the glory, you can just paste your code sample in here and which file it goes into, and someone else could submit it for review and a merge request. I could really use this feature.

**Comment by ptwobrussell** [comment]
Just wanted to pile on and suggest that in additional to creating a new
blank spreadsheet, copying an existing spreadsheet would also be a nice
option.

Given the new requirement to exclusively use OAuth as of late, along with
the requirement to explicitly share the spreadsheet with the "email
address" in the OAuth credentials before it can be programmatically
accessed, I assume that we'd want to incorporate that "sharing"
functionality into the patch as an option.

I'd be happy to help contribute some cycles here if others are also willing
to chip in...

**Comment by cstarner** [comment]
I've submitted a pull request, with the new() function added, and it's straightforward to use. The only thing you have to do is supply a title, and make sure that your OAuth 2.0 token contains the appropriate scope.

It wouldn't be too hard to implement a copy function, Google Drive API already has a copy endpoint, and it just needs the id (or key, as it is often referred to in gspread) of the spreadsheet to be copied.

**Comment by cstarner** [comment]
Though it might be harder (since multi-part form encoding isn't easy in the base Python3 library), it shouldn't be too tricky to upload a spreadsheet to Google Spreadsheets, and convert it as well. Doesn't seem like it would necessarily be very necessary in this library, but it is possible

**Comment by burnash** [comment]
Added in #253
