### ISSUE TITLE
Getting Columns to csv

### ISSUE THREAD

**Issue by isherwoodTC** [burnash/gspread#248]
i'm trying to write columns to a csv. 

~~~python
chicagotest= wks.worksheet("CHICAGO")
chicagotest1=chicagotest.range('A:K')


filename = wks.worksheet("CHICAGO").title + '.csv'
with open(filename, 'wb') as f:
    writer = csv.writer(f)
    writer.writerows(chicagotest1.get_all_values())
~~~

please help

**Comment by burnash** [comment]
Sorry for the late reply. 

The `chicagotest1` in your snippet is just an array of `Cell` objects. It doesn't have the `get_all_values` method (which belongs to the `Worksheet` class.) That's why your code is failing.

I don't know how big is your spreadsheet, but try to call `get_all_values` on `chicagotest` and then filter out not relevant data. Unfortunately there's still no way to get values by rows from spreadsheet's ranges.
