### ISSUE TITLE
Sheet generation is slow

### ISSUE THREAD

**Issue by Opalo** [burnash/gspread#267]
Hi,

When I'm adding new spreadsheet it takes about 12 seconds add a single row with 10 columns - it's very slow. I'm using `update_cell` for every cell being added in a single row. Is it possible to speed it up? If so, how?

**Comment by Shiva-Shinde** [comment]
Hi @Opalo 

Are you using nested for loops? or any function with heavy instructions (like loops). Update_cells and update_cell are both pretty quick. 

Adding a new spreadsheet should take not more than 5 sec. 12 sec is long, there might be some extra piece in your code delaying it.

**Comment by bryanweingarten** [comment]
I agree with @Opalo,  adding a new row is taking a very long time.   The following code takes between 16 and 20 seconds per insert.  I've tried this using `add_row()` and `update_cells()` and it takes around the same time too.  

```
for i in range(10):
    t = time.time()
    comparison_ws.insert_row(('A', 'B', 'C', 'D', 'E', 'F'), i+1)
    print time.time() - t
```

**Comment by asinofsky** [comment]
I'm having a similar situation, but maybe I'm missing a faster solution. I have a pandas dataframe that I want to convert into a google sheet. Right now, the quickest way as I understand it to do this is to add a sheet as follows:

workbook.add_worksheet('name',1,1)
sheet=workbook.worksheet('name)

for i in df.index:
           sheet.append_row(df.loc[i])

It takes about 5-10 seconds per row for me. With 400+ rows and 30 columns that's a bit of a pain.

I'm a novice programmer, especially with python, so if I'm missing something obvious I appreciate the help! Also, I just want to say overall I think gspread is awesome! It would be really cool if it were easier to write to a file in bulk.

**Comment by Opalo** [comment]
Despite gspread is a good lib, this issue disallowed me to use it finally. Now I create simply CSV files and upload it directly to gdrive. It works like a charm.

**Comment by msuozzo** [comment]
I recently submitted a pull request (#283) that should greatly speed up the `insert_row` function. Until that's accepted or the issue is dealt with separately, the fix is available now on my fork (msuozzo/gspread@dba33bbdc8b0ab9205c1f7753a7648098679477b).

Essentially, the algorithm used is as follows:
* Append a blank row to the spreadsheet
* Copy all rows at or below `insert` down one row
* Copy the supplied `values` list to the `insert` row

The previous implementation performed the second step using 1 API request (so a full round trip to Google and back) per _cell_ that needed to be copied down. The fix uses batch API requests for cell query and cell update (only 2 HTTP requests in total).

**Comment by axot** [comment]
`insert_row` is extremely slow in `3.0.0`

**Comment by msuozzo** [comment]
It was even slower before. The nature of the API is such that the insert operation will be a slow one for large spreadsheets.

**Comment by xinweiliusc** [comment]
I am having same issue with append_row though... around 5~10 seconds per append... 

Is it because of the same problem?
