### ISSUE TITLE
Add timeouts to API calls

### ISSUE THREAD

**Issue by Ralithune** [burnash/gspread#280]
I'm not classically trained in programming and have learned all of my Python skills through what I would describe as "guerrilla-coding".

I'd like to set my script up to sub-thread the gspread call to get a worksheet.  In light of recent Google API issues, this will let me time out and perform a different operation instead of using gspread in cases where it's down.

However, I'm having trouble on the implementation of that - so I'm looking for advice.  All I want to do is:

• Kick off the call to get_worksheet()
• Monitor that call for a pre-determined period (something like 30 seconds)
• Timeout and continue on to something else if the timeout threshold is reached
• Have the worksheet object returned if the operation completes within the timeout period

I've tried using Multiprocessing, but the worksheet objects returned have SSL components that are "unpickleable".  I need those portions of the object so that I can manipulate the remote worksheet (I'm assuming).

Threading doesn't have a way to support object returning, only basic mutable data types like Hashes or Strings.

So - any ideas on best approach?

**Comment by msuozzo** [comment]
There's a UNIX-only solution [here](http://stackoverflow.com/a/2282656/862857). I wrote something along these lines for timing out `raw_input` which is [here](https://gist.github.com/msuozzo/2c66cc272f43600f653e). I adapted it to better suit your case:

```python
import signal
from contextlib import contextmanager

class TimeoutError(Exception):
    """Indicate a timeout"""
    pass

@contextmanager
def timeout(seconds):
    def cb_interrupt(signum, frame):
        """Raise a TimeoutError if SIGALRM is encountered"""
        if signum == signal.SIGALRM:
            raise TimeoutError
    signal.signal(signal.SIGALRM, cb_interrupt)

    # collect input
    signal.alarm(seconds)
    try:
        yield
    except TimeoutError:
        return
    else:
        # disable alarm
        signal.alarm(0)
        return

with timeout(30):
    # Call function that may hang
```

If you're set on multiprocessing, you could try a simple producer-consumer with two threads. The examples for `Queue` [in the pydoc](https://docs.python.org/2/library/multiprocessing.html) should be helpful. The basic idea would be to start one thread to make the `get_worksheet()` call and have it feed the result to a Queue on which a separate consumer thread is listening. I used [this](http://pymotw.com/2/multiprocessing/communication.html) example when I had to implement something similar.

**Comment by actioncrypto** [comment]
Also have been noticing my script hang with no timeout/error or seemingly easy way to detect when the API dies...

Please add a param in like the gspread construction that sets a timeout duration for the underlying requests sessions, which is what I suspect is randomly hanging beyond anyone's control

With the current library, I can't seem to determine when the calls to read or write data will die, and need to catch the errors some way so we can retry the call after a short while and continue on the program loop

**Comment by msuozzo** [comment]
This is a good idea. I can look into implementing this soon.

**Comment by actioncrypto** [comment]
@msuozzo please do, I'm noticing it almost once a day or every other day when either reading or writing to cells via the update_acell() and acell() --- no way to easily monitor those calls for hangs/timeouts. Basically it just freezes my script. All i need is some way to catch/kill it and retry after X seconds...

**Comment by Ralithune** [comment]
I'm pretty sure I ended up doing what Msuozzo suggested with multiprocessing - I did things the hard / messy way.

I wrote functions that get called to go and do a task, and those functions set up a multiprocessing pool that calls a worker function to run in the processing pool and be monitored for completeness.  


For example:
```python
def update_log(data_list):
     pool = multiprocessing.pool.Pool(1)
    p = pool.apply_async(gspread_update_log_worker, args=(data_list,))

    starttime = time.time()
    bail = False
    warn_flag = False
    while not bail:
        bail = True
        if not p.ready():
            bail = False
        #End if the pool process isn't ready yet
        if time.time() - starttime >= 15 and not warn_flag:
            error("gspread_update_log_worker has been hung for 15 seconds...", warn = True)
            warn_flag = True
        elif time.time() - starttime >= 30:
            error("gspread_update_log_worker has been hung for 30 seconds.  Bailing.", warn = True)
            return None
        #End if we've taken too long
    #End wait for processes to complete loop

    return p.get()
#End update_log()


def gspread_update_log_worker(mbdlist):
    try:
        #get_sheet is a function that interacts with the Gspread API and just returns a sheet
        holysheet = get_sheet(4)  
        for h in holysheet.get_all_records(head=1):
           #Does stuff with data here
        #End loop through data
    except Exception as e:
        error("Something went wrong trying to update log?  Error was:")
        error("  " + str(e))
    #End T/E
    return False
#End gspread_update_log_worker()
```

Since SSL objects are "unpickleable", I couldn't just make one pair of functions to get worksheets - I had to write a pair of separate procedures for each operation I wanted to perform.

**Comment by msuozzo** [comment]
Okay I implemented a quick and dirty timeout. #289 makes this waaaaaay simpler because I basically just ripped out `requests`' timeout handling code. I haven't written tests yet so I'm not going to open a PR right now but it's available from [my branch](https://github.com/msuozzo/gspread).

**Comment by actioncrypto** [comment]
Hey guys... so I'm not super great with git and programming in general, and trying to mod this myself to implement the changes from @msuozzo or @suminb causes all sorts of issues because now i have the 'official' pip gspread in my site packages and then also these 'local' versions that i can't seem to get being correctly used or even seen.... 

I really just want the requests timeout fixed in the official release. PLEASE, can the owner of this repo fix the timeout issue so it doesn't cause lots of headaches for me and works with pip install/upgrades?

I'd rather not go on a long learning expedition of 'how to fork' projects, and just fix the bug that is plaguing this code. I also don't want to have to maintain my own version of gspread and wish this can be taken care of real soon... 

very frustrated here... :(

**Comment by msuozzo** [comment]
Alright let's work this out.

* To remove the official gspread, `pip uninstall gpread`
* To add _either_ my branch _or_ @suminb's (_i.e._ not both), you can run the following command in pip:
```
pip install -e  git://github.com/{USERNAME}/gspread.git@{BRANCH}#egg=gspread
# For my branch, USERNAME would be `msuozzo` BRANCH would be `master`
```
* I wouldn't try to add both. If you're not comfortable with git, attempting this would likely frustrate you more than it's worth.

**Comment by actioncrypto** [comment]
Well, hot damn. All I had to do was to delete the original 'official' one first. DOH! definitely wasn't lying when saying how not-super-great I am :)

Thank you all so much for your help on this!! I have just now managed to get the new patches in by doing what @msuozzo said, since it's the same as official release + new timeout fix... will run it for awhile and see if it solves my initial problem (I'm hopeful)

Last questions... when this gets fixed in the main original gspread library, do I then uninstall this new copy and do a normal `pip install gspread` to get back to 'vanilla' ?

**Comment by msuozzo** [comment]
Fantastic!

To answer your question: No. The version in `pip` will be the older release unless you explicitly instruct it to pull from the `burnash/gspread` repository. You can either wait until a new release is tagged and uploaded or add the master branch of the repository to `pip` as I described above.

**Comment by actioncrypto** [comment]
Hmm ok, so unfortunately, it didn't quite fix the timeout problem with the new patch 'as-is'

The fix won't auto-refresh the session... instead, you have to try/catch for the error when authorizing, logging in, getting, or setting values - the timeout param (which imho should have a default of `10`, not `None`) is now available when authorizing or logging in. Once you catch the error, you must then re-authorize the API credentials and return the sheet to retry your desired action.

Curiously, I have an identical script running (before the fix) on a linux server and it has *never once* timed out (months of uptime). On my development osx laptop, it will intermittently have timeout issues.

Using the fix & the logic described above completely solves the google API timeout problem (in my use case & testing)... However, I do wonder if truly using the `requests` package underneath `gspread` instead of the patch + standard libraries used would make it even easier to deal with and auto-refresh...

**Comment by msuozzo** [comment]
@actioncrypto, yeah so it seems this kind of depends on #302. Regardless, the `timeout` option will be added when requests is merged. Shouldn't be long now.

**Comment by thiagophx** [comment]
Hey guys, I've also been experiencing the same issues with scripts just hanging and not actually doing anything. It's definitely related to connections not timing out.

Currently, I have a poor man's solution, but I would love to have a proper time out feature, as described in this PR. Any news on when it should be merge officially?

Thanks.

**Comment by Harristocles** [comment]
Hi Everyone, 
I've been using gspread for a project and found that this timeout feature would be and excellent addition. Any plan to implement this to the official build?

Cheers.

**Comment by lavigne958** [comment]
This issue as been resolved, Thank you @Ralithune  for the follow-up. 

Gspread now uses [AuthorizedSession](https://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.requests.html#google.auth.transport.requests.AuthorizedSession) which derives from `requests.sessions.Session`. 

closing this issue.
