### ISSUE TITLE
`Worksheet.insert_row` removes formulae below insertion point

### ISSUE THREAD

**Issue by msuozzo** [burnash/gspread#284]
Because the `insert_row` performs the copy with the `Cell.value` attribute (as opposed to `Cell.input_value`), all formulae at and below row `index` are lost.

I tried to simply replace `value` with `input_value` but the request failed because of what I believe to be a Sheets API error (the cell input values contained cell references in the format `R[#]C[#]` instead of the usual `A#`)

**Comment by burnash** [comment]
I went with replacing `value` with `input_value` and merged #338. Since `insert_row` copies formulas verbatim (as opposite to the row insertion in the Sheets UI, where cell refs are recalculated) it could lead to incorrect formulas. For now, I don't know any solution other than parsing formulas and essentially replicating Sheets functionality locally. But this will go way outside the scope of the library. The API v4 should change this. I think the simplest way now is to let the user handle the edge cases.

I'm closing the issue for now. Please feel free to reopen it.
