### ISSUE TITLE
Create worksheet name conflict result in error with no message

### ISSUE THREAD

**Issue by samzhang111** [burnash/gspread#359]
I propose wrapping this in a custom exception. WorksheetExistsException?

**Comment by NotLeet** [comment]
It's a pretty easy fix. I mean, the error is exactly what it says on the tin. Someone wrote an HTTPError class and then tries to show you the message on that class, but didn't actually get around to creating a message attribute.

I added a quick fix for this in my PR. #390

It just raises a RequestError using the error string that you get back from the Google API, which tend to be pretty reliable and informative.

I'm not sure when or if my PR will get merged, but if it doesn't it should be a pretty easy thing to fix regardless.

**Comment by lavigne958** [comment]
This is not the case anymore. Did a test:
- create a spreadSheet with new name "Test1" => :heavy_check_mark:
- run the script again and create a spreadSheet with the same name => :heavy_check_mark: 

this is due to the following rule in Google API: "he name of the file. This is not necessarily unique within a folder." [here](https://developers.google.com/drive/api/v3/reference/files/create#request-body)

This means you can create multiple files with the same name in a single folder, they will all have different IDs.

What could be useful here is an option like: "fail if already exists", before the actual HTTP call, gspread could check for a file existence of the same name (and returns its id in this case, or open the actual file, to be thought through).

**Comment by lavigne958** [comment]
Using new GoogleAPI this is not relevant anymore.

Closing this issue.
