### ISSUE TITLE
Feature Request: Change the colour of a cell worksheet.cell_colour(cell, colour)

### ISSUE THREAD

**Issue by KingMuffin11** [burnash/gspread#446]
I feel like this could be a pretty useful feature. Please let me know if this is already a thing

**Comment by burnash** [comment]
Thank you for the suggestion. Since gspread version [3.3.0](https://github.com/burnash/gspread/blob/master/HISTORY.rst#330-2020-03-12) you can change  the format of a cell with `Worksheet.format()` method.

Example:

```python

# Makes cell background red
worksheet.format("A1:C1", {"backgroundColor": {"red": 1, "green": 0, "blue": 0}})
```

Other format options available in the [Sheets API reference](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#CellFormat).
