### ISSUE TITLE
Issues sending data to Google after creating 2nd credentials file

### ISSUE THREAD

**Issue by bwatkin79** [burnash/gspread#450]
I had 2 programs that were working perfectly until I created another JSON credentials file in Google to use with gspread. My plan was to use the new credentials file for a different project. Ever since I did this though, my original 2 programs have an issue posting all of the data before the credentials expire at an hour. They were not having an issue with the time before and the issue started at the same time for both programs. My programs appear to be working correctly otherwise because they are still retrieving their data as designed. Since I was having issues, I deleted the second credentials, but it hasn't helped.

Did I screw up something somehow? Anyone else having this issue?

### Environment info

Operating System: Windows 7
Python version: 3.5
gspread version: Not sure

**Comment by bwatkin79** [comment]
I just created a new Google account and created new credentials to see what would happen. I selected the Compute Engine default, which I think I used create New Service account last time. I sent the data into a new spreadsheet in this Google account and the full table of data imported. Does a large amount of formulas slow down importing data? Several formulas reference what I'm importing, so it's making me wonder.

**Comment by lavigne958** [comment]
Hi @bwatkin79 I'm glad you solved your issue.
The authentification process is now changed to latest Google Auth system.

A lot of formulas might slow down a bit if you get your values with the result of the formula, because it takes a little bit more of computation to compute the formula result, but that's OK Google's side so don't worry too much they have what it takes to do the job 😊. What can be slow is having a lot of datas, as a lot of actual rows/columns. 

Issue is solved.
Closing this issue
