### ISSUE TITLE
OAuth documentation needs clarification or update

### ISSUE THREAD

**Issue by fenhl** [burnash/gspread#484]
The OAuth documentation at http://gspread.readthedocs.io/en/latest/oauth2.html says to look for “API & auth”. However, this text does not appear on the linked webpage.

**Comment by crccheck** [comment]
I'm working through this myself and there's a bunch of information on that page that needs updating. I went ahead and copied the unmaintained docs to the wiki https://github.com/burnash/gspread/wiki/Using-OAuth2-for-Authorization

I already have a key file so I can't speak to the section you're having trouble with, but I can say that Google redesigns that page every couple of months so it's pretty much guaranteed to always be out of date no matter how much work you put into it :(

**Comment by xloem** [comment]
Has anybody figured out how to get a new signed key?  Does google need payment now?

**Comment by xloem** [comment]
This wizard is helpful: https://console.developers.google.com/start/api?id=sheets.googleapis.com .

**Comment by burnash** [comment]
Thanks for the input to everyone. I believe this issue is resolved now in #706

Sometimes it's hard to keep up with UI changes in Google Console. So contributions to the docs are always welcome.

@crccheck Thanks for creating the wiki page. I'm now considering taking down Wiki pages to consolidate all documentation in one place. This ticket is a bit outdated, documentation is now on Readthedocs, and each page has "Edit on GitHub" link. Which turns it into Wiki. (Except for slight formatting difference).

@xloem Thanks for the link.
