### ISSUE TITLE
Unable to login and get spreadsheet

### ISSUE THREAD

**Issue by keawepoo** [burnash/gspread#565]
### Environment info

Operating System: RPI
Python version: 2.7.13/3.5.3
gspread version: 3.01

### Steps to reproduce
Same issue as [https://github.com/burnash/gspread/issues/246]( https://github.com/burnash/gspread/issues/246) all the way up to adding the try / except wrapper. 

### Stack trace or other output that would be helpful
```
Logging sensor measurements to Humidity every 30 seconds.
Press Ctrl-C to quit.
Unable to login and get spreadsheet.  Check OAuth credentials, spreadsheet name, and make sure spreadsheet is shared to the client_email address in the OAuth .json file!
('Google sheet login failed with error:', APIError(u'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "insufficientPermissions",\n    "message": "Insufficient Permission"\n   }\n  ],\n  "code": 403,\n  "message": "Insufficient Permission"\n }\n}\n',))
```
[Json file](https://gist.github.com/keawepoo/138f26b2e680bd58d84bc507db38fa4d)
[Sharing settings](https://i.imgur.com/AoAdsvF.jpg)

Thank you.

**Comment by daN4cat** [comment]
@keawepoo I found out from #512 that you need to add in the scope the following `'https://www.googleapis.com/auth/drive'`.

After that you might face an append issue and I suggest to read the following thread to get that sorted: https://forums.adafruit.com/viewtopic.php?p=677581.

It's due to `datetime.datetime.now()` and I solved following this: https://forums.adafruit.com/viewtopic.php?f=19&t=53299&start=120

Read even #511 for more info about that issue.

I believe this issue can be closed.

**Comment by burnash** [comment]
@keawepoo Thanks for the answer. Closing the issue.
