### ISSUE TITLE
[error] E1121:Too many positional arguments for method call

### ISSUE THREAD

**Issue by Rivareus24** [burnash/gspread#601]
### Environment info

Operating System: Windows 10
Python version: 3.7.0
gspread version: 3.0.1

### Documentation
![chrome_2018-10-08_11-32-50](https://user-images.githubusercontent.com/17569017/46601805-9bd11c00-caee-11e8-9499-6289a7cd25ac.png)

### Steps to reproduce
1. [GET WORKSHEET]
WS = gc.open(SPREADSHEET_NAME).worksheet(WORKSHEET_NAME)

2. [GET RANGE]
range= WS.range(int, int, int, int)                            {{error}}

### Error
E1121:Too many positional arguments for method call

**Comment by burnash** [comment]
Sorry for the late response. I'm following the steps to reproduce the error with the latest version of gspread (3.3.0). At the moment I can't reproduce the error. 
Since this is an old issue so I'm closing it for now. Please upgrade gspread to the latest version and try again.
If you still experience the issue, please create a new ticket.
