### ISSUE TITLE
get_all_records vs get_all_values different interpretation of value types

### ISSUE THREAD

**Issue by hatani** [burnash/gspread#644]
Seems like both methods evaluate values differently.  If googlesheet cell contains 'a number' (e.g.: 3.5), it gets intepreted as float by **get_all_records()** while **get_all_values()** returns a string ('3.5').

Examples:
>>> sh.get_all_values()
[['Tier', 'Fiber', 'Cloth', 'Hide', 'Leather', 'Ore', 'Bar', 'Wood', 'Plank'], [**'3.0',** '110', '', '', '', '', '', '', '']....]

>>> sh.get_all_records()
[{'Tier': **3.0**, 'Fiber': 110, 'Cloth': '', 'Hide': '', 'Leather': '', 'Ore': '', 'Bar': '', 'Wood': '', 'Plank': ''}, ....]

Operating System: Linux Antergos
Python version: 3.7.2
gspread version: 3.0.1

If this is duplicated or even intended, please just close the bug report.

EDIT: Same behavior in gspread 3.1.0 as well.

**Comment by burnash** [comment]
Thank you for the report. Yes, this is expected behavior.  `get_all_values()` returns the values fetched from the Sheets API as is. While `get_all_records()` does some additional processing with numbers.
Mode details in the docs: https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Worksheet.get_all_records

I'm closing this for now. If the docs need to be more explicit about the difference, documentation improvements are always welcome :)
