### ISSUE TITLE
Must a spreadsheet be shared?

### ISSUE THREAD

**Issue by irthomasthomas** [burnash/gspread#656]
Hello, I'm just reading the docs and I note it asks me to share a spreadsheet first. Is it necessary to share every spreadsheet I want to use?

Cheers

**Comment by lavigne958** [comment]
Hello @irthomasthomas 
Yes it is necessary, in order to access Google API you must first be authenticated.
This (in the case of a script, using the API) can only be done using a special account or in behalf of a real human account.

In that case you must first share the spreadsheet you want to edit/delete/update with that special account.
If you wish to craete spreadSheets with that special account, they only be visible from that account. The same way the spreadSheets I create are only visible to me, not to you or my friendly neighbor :smile: in that case you must share that new spreadsheet with your personal account in order to access it.

I will close this issue but you can still ask your questions here if something is unclear.

Closing this issue.
