### ISSUE TITLE
GSpread Error 429

### ISSUE THREAD

**Issue by AETDDraper** [burnash/gspread#764]
**Important**: Please do not post usage questions here. 
To get a quick response, please ask a question on Stack Overflow using `gspread` tag.
See existing questions: https://stackoverflow.com/questions/tagged/gspread

---

**Describe the bug**

Error I am getting when clearing and then updating 15 Sheets. Roughly 1000 rows and 10 columns for each in a loop. 

Do i need to add a backoff is there a way around this?

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Code example***
If applicable, provide a code example to help explain your problem.

**Screenshots**

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]:
- Python version
- gspread version

**Stack trace or other output that would be helpful**

**Additional context**

**Comment by lavigne958** [comment]
Hello, I would advise you fill up the issue template so everyone looking at it can have enough details to reproduce the issue and provide you with the necessary help.

This is just an advise.

**Comment by aiguofer** [comment]
This is documented in the Google Sheets API: https://developers.google.com/sheets/api/limits

I implemented a retry for the 100s quota breach in: https://github.com/aiguofer/gspread-pandas/blob/master/gspread_pandas/util.py#L288

I'd be happy to port it over to gspread

**Comment by burnash** [comment]
Yeah, I've started getting 429 recently while running the test suite and implemented a derived `Client` class very similar to the [monkey patched](https://github.com/aiguofer/gspread-pandas/blob/master/gspread_pandas/util.py#L288)  in dbdf85a386b6aecac52ec168420f2307409ef307

I haven't yet made up my mind if this should be the default behavior in gspread. The problem is that it may not be clear to gspread users how many requests each method produces (see #770) which may lead to inefficient code that fetches values from single cells in a loop. 

The OP says:

> Roughly 1000 rows and 10 columns for each in a loop.

@AETDDraper could you please share a snippet of the code you're running?

**Comment by manmartgarc** [comment]
Thanks for getting this started. Is there a way to map each method to the number of requests it generates? I am running a super simple script that keeps hitting the 429 limit. Thanks

**Comment by lavigne958** [comment]
Hi we recently introduced a new `BackOffClient` and a way to use it in gspread with almost no changes.

You can now use the following code to make any requests go through the back-off client. The client will retry exponentially until it reaches some limits to make sure the client is not stuck in a loop.

use the following syntax:

```python
gc = gspread.service_account(client_factory=BackoffClient)
```

or

```python
gc = gspread.oauth(client_factory=BackoffClient)
```

closing this issue.
