### ISSUE TITLE
Add Option to add_protected_range That Does Not Include Sheet Editors

### ISSUE THREAD

**Issue by BenHagan** [burnash/gspread#793]
**Is your feature request related to a problem? Please describe.**
I'm having to use batch_update to add a protected range that does not include the sheet editors since add_protected_range adds all editors by default with no ability to override.

**Describe the solution you'd like**
add_protected_range should have an option to specify explicitly which email addresses to add or an option does not also add the sheet editors by default.

**Describe alternatives you've considered**
The only alternate solution I can come up with is to do a batch_update with a custom request that does not include sheet editors.

I'll be willing to submit a PR for this if y'all can provide direction as to how you would like the solution to be implemented.

**Comment by h-kouame** [comment]
I am also facing a use case that requires this feature to be implemented.
One way this could be implemented would be to add another parameter to specify whether or not we only want the users specified in the `editor_users_emails` and `editor_groups_emails` to have access to the protected range.
Currently, it assumes that those users should simply be added to the existing editors lists as shown (see https://github.com/burnash/gspread/blob/master/gspread/models.py#L1613).
This feature would be nice because gsheets interface supports it.

**Comment by lavigne958** [comment]
Hi this has been fixed since then, please upgrade to the latest version of gspread it includes a fix, you can now provide the list of users editors when creating the protected range. 

Remember: you must include yourself (the account accessing the protecting range) in the list otherwise the request will fail.

closing this issue.
