### ISSUE TITLE
worksheet.get() fails when there's no date instead of returning empty data

### ISSUE THREAD

**Issue by AlexeyDmitriev** [burnash/gspread#800]
**Important**: Please do not post usage questions here. 
To get a quick response, please ask a question on Stack Overflow using `gspread` tag.
See existing questions: https://stackoverflow.com/questions/tagged/gspread

---

**Describe the bug**

**To Reproduce**
1. Create empty worksheet
2. Call worksheet.get('A1') or worksheet.get('')
3. 

**Expected behavior**
Empty list [] is successfully returned (0 rows)

**Environment info:**
Python 3.8
gspread 3.6
Mac OS

**Stack trace or other output that would be helpful**

```
Traceback (most recent call last):
  File "/Users/alexeyd/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/201.8538.36/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/gspread/utils.py", line 592, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/gspread/models.py", line 965, in get
    return ValueRange.from_json(response)
  File "/usr/local/lib/python3.8/site-packages/gspread/models.py", line 51, in from_json
    new_obj = cls(json['values'])
KeyError: 'values'
```

**Additional context**

**Comment by burnash** [comment]
Thank you for reporting this. It's fixed in #791. The fix will be on PyPI with the next release (soon).

**Comment by CH-EricLundberg** [comment]
Any update on when this will get released?

**Comment by lavigne958** [comment]
The above PR has been merged. Since all the following releases will include the necessary fix:

- [v5.3.0](https://github.com/burnash/gspread/releases/tag/v5.3.0)
- [v5.2.0](https://github.com/burnash/gspread/releases/tag/v5.2.0)
- [v5.1.1](https://github.com/burnash/gspread/releases/tag/v5.1.1)
- [v5.1.0](https://github.com/burnash/gspread/releases/tag/v5.1.0)
- [v5.0.0](https://github.com/burnash/gspread/releases/tag/v5.0.0)
- [v4.0.1](https://github.com/burnash/gspread/releases/tag/v4.0.1)
- [v4.0.0](https://github.com/burnash/gspread/releases/tag/v4.0.0)
- [v3.7.0](https://github.com/burnash/gspread/releases/tag/v3.7.0)

**Comment by lavigne958** [comment]
The above PR has been merged. Since all the following releases will include the necessary fix:

- [v5.3.0](https://github.com/burnash/gspread/releases/tag/v5.3.0)
- [v5.2.0](https://github.com/burnash/gspread/releases/tag/v5.2.0)
- [v5.1.1](https://github.com/burnash/gspread/releases/tag/v5.1.1)
- [v5.1.0](https://github.com/burnash/gspread/releases/tag/v5.1.0)
- [v5.0.0](https://github.com/burnash/gspread/releases/tag/v5.0.0)
- [v4.0.1](https://github.com/burnash/gspread/releases/tag/v4.0.1)
- [v4.0.0](https://github.com/burnash/gspread/releases/tag/v4.0.0)
- [v3.7.0](https://github.com/burnash/gspread/releases/tag/v3.7.0)
