### ISSUE TITLE
GSpread pulling back information from original spreadsheet, not copied one

### ISSUE THREAD

**Issue by jatsad** [burnash/gspread#852]
Hi,

I have a situation where I was successfully pulling information from spreadsheet FY21 XXXX.
Spreadsheet FY21 XXXX was copied to spreadsheet FY22 XXXX.
Trying to pull information from FY22 XXXX returns information from FY21 XXXX.

I am using the Python DE Pycharm which allows step by step debugging. 

The code is shown below:

    spreadsheet_url = "https://docs.google.com/spreadsheets/d/187Qf-BKG81odXcX95cKmp8Iuzny86pD0NQEjnh25AfQ/edit?ts=6026e2b8#gid=451669773"

    client = gspread.authorize(creds)
    sheet = client.open_by_url(spreadsheet_url).sheet1  # Open the spreadsheet
    row = 9
    col = 306
    cell = sheet.cell(row, col).value  # Get the value of a specific cell
    return cell

I have stepped through the program to the "row = 9" code.

Details are in the attached 

As you can see, although the spreadsheet is FY22 XXXX, tab title shows "FY21" and the id is that of FY21 - 1750045356. 
Id of FY22 is 451669773.
The URL shown is where I think the issue is. It has the correct key but has the id of FY21, not FY22 which can be seen in spreadsheet_url.

As shown in the attached screenshot next to the "sheet = client.open code, it is showing details of FY21.
![Screen Shot 2021-03-24 at 6 17 28 pm](https://user-images.githubusercontent.com/38587059/112269992-39276700-8ccd-11eb-82ba-d80d8c7ff864.png)

**Comment by jatsad** [comment]
Anyone?

**Comment by jatsad** [comment]
Is anyone going to comment?

**Comment by lavigne958** [comment]
Hi @jatsad 

Thank you for pointing out this issue. I still need to investigate and run some tests.

**Comment by lavigne958** [comment]
Did you use the gspread `copy` method to copy the spreadsheet or did you copy it using the web UI drive.google.com?

**Comment by lavigne958** [comment]
Hi @jatsad thanks for taking a look at this.

I don't see any issue here. 
I tried running the same code, copy a spreadsheet, then open it and everything seems fine.

I looked at your screenshots, everything seems fine too.
You open a spreadsheet with the ID: `187Qf-BKG81odXcX95cKmp8Iuzny86pD0NQEjnh25AfQ`
When you look at the variable `url` it contains the same ID.
what you see in the next to `sheet = {Worksheet}` is the name of the sheet itself, and it's ID.
It is fine because when you copy the spreadsheet you copy all it's sheets and they keep the same name.
When you look at the line `spreadsheet = {Spreadsheet} ...` you see the right spreadsheet name with FY22 and the same ID as the one you open.

I don't see any issue.
Closing this issue.
