### ISSUE TITLE
`get_values` does not return all data in some scenarios with empty data

### ISSUE THREAD

**Issue by kyle-tc** [burnash/gspread#910]
Hello! Thanks for your time. I wanted to report a potential bug in the `get_values` function. When you have a spreadsheet that has say 6 columns with headers, where data should be and you make a query for a particular row, there is a certain scenario where empty data fields are not returned. This can be confusing for downstream users of the gspread API who want to say, convert the row into a dictionary (ala `get_all_records`).

This scenario occurs when data is laid out like this:

```
header1, header2, header3, header4, header5, header6
x1, , , x4, ,
```

In that data above header5 and header6 are empty for the first row. Suppose you made this call:

```
ws.get_values("A1:1")
```

You only get back:

```
[['x1',,,'x4']]
```

As opposed to what I would expect:

```
[['x1',,,'x4',,]]
```

Minimal reproducer:

<img width="815" alt="Screen Shot 2021-08-17 at 11 17 03 AM" src="https://user-images.githubusercontent.com/88736977/129753355-29c19f04-4d20-4dbd-a3e8-e5013b8ec5c5.png">

```
(Pdb++) ws.get_values("A7:7")
[['', 'kl3020', '', '07/26/2021']]
```

Expected result:

```
(Pdb++) ws.get_values("A7:7")
[['', 'kl3020', '', '07/26/2021', '', '']]
```

**Comment by kyle-tc** [comment]
Furthermore `get_all_records` works exactly as expected in this scenario.

**Comment by lavigne958** [comment]
Hi @kyle-tc ,

thank you for reporting this issue.

I ran some tests an noticed the resulting length of the list returned can vary depending on the longest row with non empty cells that is returned. for example if your call to  `get_values` includes your headers then the headers is the longest list of non empty values (6 values in total) so any row below/above will be of length 6. If you request some value in the middle of your spreadsheet and it only contains 4 non empty values then the list will be of length 4.

This is due to SpreadSheet API that returns a list of values for each row that is returned and trims empty values at the begining and the end.

Gspread made a workaround that by finding the longest row in the all the results then making sure all the list of values returned are of the same length. But you still need to retrieve one full line to obtain all your empty cells in all rows.

Hope this is not too confusing :laughing:  if so please comment here and I'll clarify any thing that is unclear :slightly_smiling_face:

**Comment by wgwz** [comment]
hey @lavigne958 :wave: (replying from my other account). That makes sense, and I see why it would work that way. It makes me wish that header rows were a first class concept in google spreadsheets. But alas, I guess these types of headaches are to be expected if you're using spreadsheets as a database. I think in my case, I'll standardize on pulling in the first row of data and following a similar procedure to what you mentioned about padding rows that are shorter than the header row with empty values. i'm tempted to say that it would be nice to bake this feature into gspread but i'm sure that would be a backwards compatibility issue as it forces users to use the first row as headers, or there are people who have built other ways around it. perhaps it could be added as a opt-in functionality... but still i can see why it's tricky.

but the whole reason i actually went down this path was because i was hoping that the "find text" function was an API call to google that offloaded the search onto googles servers. then i noticed that we are just making a call to "get all records" anyways, so it was a bit pointless. i don't mean to change topic from the issue that i reported. but maybe it will be helpful for someone else searching google in the future. do you know if there is an API that does that with spreadsheets? i'm pretty sure the answer is no but admittedly i didn't look to hard once i realized what the search functions in gspread were doing.

**Comment by alifeee** [comment]
superceded by #1289
