### ISSUE TITLE
Has anyone done code analysis on this project ?

### ISSUE THREAD

**Issue by m00dy** [burnash/gspread#927]
This project could be a goodspot to inject some sort of backdoor to analyze documents on the fly. Has anyone done audit on the code itself ?

**Comment by burnash** [comment]
I guess this is a good question to ask yourself when you're installing *anything* from the internet :) 
The second question is if you trust *anyone* who does audit for you. 
It's always a good idea to check what you're installing on your machine. 

Since it's an open source project you can look at the source code and see what it does. If you install gspread from PyPI (https://pypi.org/project/gspread/) you may check the package contents before you install it. You would also need to check the packages gspread depends on (see https://github.com/burnash/gspread/blob/master/setup.py#L47). 
Same thing if you're installing the package from GitHub.
