### ISSUE TITLE
Option to access Sheets API using Google client library?

### ISSUE THREAD

**Issue by ajw-42** [burnash/gspread#931]
As far as I can tell, you're always hitting the Sheets API using the URLs in `urls.py`. I have some projects where I'm querying the API using the `google-api-python-client` library, but I'd still like to use `gspread`'s helpful tools for manipulating data before/after the API call. Is there a reason you don't support that approach or why the URLs are a better option?

I ran a few speed tests comparing `gspread.Spreadsheet` methods with their Google client library equivalent, for example `spreadsheet.values_batch_update()` vs `google_client.sheets.values().batchUpdate().execute()` -- and the client library is a bit slower, so maybe this is why you chose the URLs.

Thanks!

**Comment by lavigne958** [comment]
Hi @ajw-42

I thought about it, using the python library but the gspread owner explained that Google can make some changes and depreciate come library like this is is only in maintainance mode, the owner of Google python apitm client recommend using a different library.

You can find the following ticket that was my intention to replace the url by the library and I finally changed my mind to keep the pure http access.
See #984

**Comment by burnash** [comment]
Just wanted to expand on @lavigne958 answer. 

Currently gspread uses vanilla HTTP for legacy reasons. When I started gspread it was a wrapper around Google's gdata (a predecessor to google-api-python-client). After a while I dropped the dependancy. It was a long time ago and unfortunately I don't remember the rationale behind this (I didn't document this 🙄). I believe this was some sort of optimization as pre v4 Sheets API was XML based. I kept the pure HTTP access when I ported the library to Sheets v4.

As @lavigne958 mentioned there was an idea of bringing in google-api-python-client, however after consideration we decided against this. 1) [google-api-python-client](https://github.com/googleapis/google-api-python-client#google-api-client) is now in maintenance mode. 2) Since it's a single client for all Google API it's quite heavy. 3) It brings in more levels of abstraction. Currently it's quite easy to see what's going on with your Sheets API request as gspread code is pretty straightforward (maybe even too much in some cases). This helps if you're concerned about security #927 and want to see what's under the hood without digging in too deep.

What kind of tools you're using from gspread and why it's not possible to use them along google-api-python-client?

**Comment by ajw-42** [comment]
Apologies for missing #894, and thank you both for the explanation. That all makes sense to me, I'll close this issue now.

I should have been clearer, I don't see any problem with using gspread alongside the client library - I just wanted to understand the thinking behind the pure HTTP access. So thanks again for explaining!
